# Generated by Django 5.0 on 2024-01-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movieshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='movieshow/images')),
            ],
        ),
    ]
